config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
 

  # Defines the root path route ("/")
  # root "articles#index"
    root  to:"main#index"

    # /about
    get "/about-us", to:"about#index", as: "about"

    # /Sign_Up
    get "/sign_up", to:"registration#new"
    post "/sign_up", to:"registration#create"

    # /Sign_In
    get "/sign_in", to:"session#new"
    post "/sign_in", to:"session#create"

    # /Log_Out
    get "/logout", to:"session#new"
    delete "/logout", to: "session#remove"

    #Rest/Forget _Password
    get "/password", to:"password#edit", as: :edit_password
    patch "/password", to:"password#update"
    get "/password/reset", to: "password#new_reset"
    post "/password/reset", to: "password#create_reset"
    get "/password/reset/edit", to: "password#edit_reset"
    post "/password/reset/edit", to: "password#edit_reset"
    patch "/password/reset/update", to: "password#update_reset"

    #List Jobs
    get "/jobs", to: "jobs#fetch_jobs"

    #List/Add_Job --> Admin Only For Now :D
    get"/jobs/recruiter_applications", to:"jobs#applications_view"

    post "/jobs/add_job", to:"jobs#create_job_post"
    get "/jobs/add_job", to:"jobs#new"
    get "/test", to:"companies#test"
    get "/test/new", to:"companies#new"

    # /Apply Jobs
    get "/jobs/Apply_Job", to:"jobs#new"
    post "/jobs/Apply_Job", to:"jobs#apply_job"

    # /Applied 
    get "/jobs/Applied_jobs", to:"jobs#fetch_applied"
    delete "/jobs/Applied_jobs", to:"jobs#remove"




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/companies.rb
class Companies <  ActiveRecord::Base
has_many :jobs
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
attribute :user
end

app/models/job_apply.rb
class JobApply <  ActiveRecord::Base
  belongs_to :companies
  has_many :users
end

app/models/jobs.rb
class Jobs <  ActiveRecord::Base
    belongs_to :companies
end

app/models/users.rb
# email:t.string 
# password_digest:string

# password:string virtual
# password_confirmation:string virtual

class Users <  ActiveRecord::Base
    has_secure_password
    has_many :jobs
    has_many :job_apply
    validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message:"must be a valid email address!!"}
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
#Our Action
def index
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user

    def set_current_user
        if session[:user_id]
        Current.user=Users.find_by(id: session[:user_id])#find will throu an error if the logged in user in the session not in the db any more!
        end
    end

    def require_user_logged_in! 
        redirect_to sign_in_path, alert: "You must be signed in!!" if Current.user.nil?
    end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  
def new
  @companies=Companies.new
end
def get_by_id 
  company = Companies.find_by(id: params[:id])
end
def fetch_all
end
def test
  @companies=Companies.all
end


end

app/controllers/job_apply_controller.rb
class JobApplyController < ApplicationController
    def get_by_id 
        company = JobApply.find_by(id: params[:id])
      end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def get_by_id 
    company = Jobs.find_by(id: params[:id])
  end
#TODO 
def new
  @job_applies=JobApply.new
  @job_applies.save
  render :create_job_post
end

def fetch_jobs
@job=Jobs.all
end
 
def create_job_post
  
  if Current.user.recruiter?
    redirect_to jobs_recruiter_applications_path, notice: "Created Successfully"
       else

        redirect_to root_path, alert:"Your not allowed to see this page !!"
       end
end

def applications_view
  # user=Users.find_by(email: params[:email])
  @job_applies= JobApply.all
  # (:conditions => { :available => true })
  # JobApply.find_by(id: [:user_id])
end


def fetch_applied
  # Jobs.all(:conditions => { :available => true })
  @job= JobApply.all
end

private

def application_params
params.require(:job_apply).permit(:recruiter, :name, :position, :experience, :email, :attachment, :describtion) #specify the exact attribute allowed for the user
end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
def index
    @job=Jobs.all
end
end

app/controllers/password_controller.rb
class PasswordController < ApplicationController
before_action :require_user_logged_in!

def edit 
end

def update
   if Current.user.update(password_params)
redirect_to root_path, notice: "Password Updated!!"
   else
render :edit
   end
end

def new_reset
end

def create_reset
    @user=Users.find_by(email: params[:email])
    if @user.present?
        #send email
        PasswordMailer.with(user: @user).reset.deliver_now
        redirect_to root_path, notice:"email was sent to #{:email}"
    end
end


def edit_reset
   @user=Users.find_signed!(params[:token], purpose: "password_reset" )
      # :token to authinticate if this is the user who requested to reset/forget password
      # binding.irb : inspect 
rescue ActiveSupport::MessageVerifier::InvalidSignture 
   redirect_to sign_in_path, alert:"Your Token Has Expired Please Try Again!!"
end
def update_reset
   @user=Users.find_signed!(params[:token], purpose: "password_reset" )
   if @user.update(password_params)
      redirect_to sign_in_path, notice: "Your Password Was Reset Successfully!!"
   else
     render :edit_reset
   end
end

  private
  
  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end

end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
def new
@user=Users.new
end


def create
    # render params =
    #  Parameters: {"authenticity_token"=>"[FILTERED]", "user"=>{"email"=>"", "password"=>"[FILTERED]", "Password_Confirmation"=>"[FILTERED]"}, "commit"=>"Submit"}
   # @user=User.new(params[:user]) # user params ={"email"=>"", "password"=>"[FILTERED]", "Password_Confirmation"=>"[FILTERED]"}
    @user=Users.new(user_params)
    if @user.save
        # cookie[:user_id]
        session[:user_id]=@user.id
        redirect_to root_path, notice: "Created Successfully"
    else
        render :new
    end

end


private


def user_params
params.require(:users).permit(:email, :password, :password_confirmation, :recruiter) #specify the exact attribute allowed for the user
end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

    def new
    end

    def create
            user=Users.find_by(email: params[:email])
            if user.present? && user.authenticate(params[:password])
                Current.user=user
                session[:user_id] = user.id
                redirect_to root_path, notice: "Logged In ..."
            else
                flash[:alert]= "invalid email or password"
                render :new
            end
    end

    def remove
        session[:user_id] = nil
        redirect_to sign_in_path, notice: "Logged Out!!"
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb

  <%= render partial: "shared/card" %>


app/views/companies/new.html.erb
<h1>H!</h1>

app/views/jobs/applications_view.html.erb
<div class="card text-center">
<% @job_applies.each do |applied| %>
    <%= form_with model:@job_applies, url: password_reset_path do |form| %>
  <div class="card-header">
    <%=applied.name%>
  </div>
  <div class="card-body">
    <h5 class="card-title">Has a <%= applied.experiance %> experience in <%= applied.position %>  </h5>
    <p class="card-text" style="margin-left:auto; margin-right:auto; width:60%; height: 200px; overflow-y: scroll;"> <%= applied.describtion %> </p>
  </div>
  <div class="card-footer text-muted">
    <%= applied.created_at %>
    <%= form.submit "Email", class:"btn btn-success" %>
    <% end %>
    <% end %>
  </div>
</div>

app/views/jobs/create_job_post.html.erb
<div class="container">
  <div class="row mx-0 justify-content-center">
    <div class="col-md-7 col-lg-5 px-lg-2 col-xl-4 px-xl-0 px-xxl-3">
<%= form_with model:@job_applies, url: jobs_add_job_path  do |form| %>
        <label class="d-block mb-4">
          <span class="form-label d-block">Your name</span>
<%= form.text_field :name, class:"form-control" %>
        </label>

        <label class="d-block mb-4">
          <span class="form-label d-block">Email address</span>
<%= form.text_field :email, class: "form-control", placeholder: "ashqur@zen.com" %>
        </label>
                <label class="d-block mb-4">
          <span class="form-label d-block">Position</span>
<%= form.text_field :position, class:"form-control" %>
        </label>

        <label class="d-block mb-4">
          <span class="form-label d-block">Years of experience</span>
          
          <%= form.select :experience, options_for_select([["Select One", ""],"Less than a year", "1 - 2 years", "2 - 4 years", "4 - 7 years", "10+ years"]), class:"form-select" %>
        <label class="d-block mb-4">
          <span class="form-label d-block">Tell us more about yourself</span>
          <%= form.text_area :describtion, class:"form_control", rows:"3",size: "50x5", placeholder:"What motivates you?" %>
        </label>

        <label class="d-block mb-4">
          <span class="form-label d-block">Your Resume</span>
<%= form.file_field :attachment, :multiple => true %>
        </label>

        <div class="mb-4">
          <div>
            <div class="form-check">
              <label class="d-block">
                <span class="form-check-label">You'd like to work remotely</span>
                <%= form.radio_button :remotly , class:"form-check-input"  %>
              </label>
            </div>
          </div>
        </div>
        <div class="mb-4">
          <div>
            <div class="form-check">
              <label class="d-block">
                <span class="form-check-label">You'd prefer to work onsite</span>
                <%= form.radio_button :remotly , class:"form-check-input"  %>
              </label>
            </div>
          </div>
        </div>


        <div class="mb-3">
           <%= form.submit "Apply", class:"btn btn-primary px-3 rounded-3" %>
        </div>

        <div class="d-block text-end">
          <div class="small">
            by
            <a
              href="https://herotofu.com"
              class="text-dark text-decoration-none"
              target="_blank"
              >HeroTofu</a>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/jobs/fetch_applied.html.erb
<div class="card text-center">
    <% @job.each do |s| %>
  <div class="card-header">
    <%= s.name %>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= s.position %></h5>
    <p class="card-text" style="margin-left:auto; margin-right:auto; width:60%; height: 200px; overflow-y: scroll;"> <%= s.describtion %> </p>
  </div>
  <div class="card-footer text-muted">
    <%= s.created_at %>
    <% end %>
  </div>
</div>

app/views/jobs/fetch_jobs.html.erb
<br>
<div class=".container-fluid">
<% @job.each do |s| %>
    <%= form_with model:@job, url:  jobs_Applied_jobs_path do |form| %>
    <div class="alert alert-success" role="alert" >
  <h4 class="alert-heading"><%= s.title %></h4>
  <hr>
  <p style="margin-left:auto; margin-right:auto; width:60%; height: 200px; overflow-y: scroll;"> <%= s.description %> </p>
  <hr>
  <p class="mb-2"><%= s.created_at %> </p><%= form.submit "Apply", class:"btn btn-primary" %>
</div>
<% end %>
<% end %>
</div>

app/views/jobs/post_job.html.erb
<form class="row g-3">
  <div class="col-md-6">
    <label for="inputEmail4" class="form-label">Email</label>
    <input type="email" class="form-control" id="inputEmail4">
  </div>
  <div class="col-md-6">
    <label for="inputPassword4" class="form-label">Password</label>
    <input type="password" class="form-control" id="inputPassword4">
  </div>
  <div class="col-12">
    <label for="inputAddress" class="form-label">Address</label>
    <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">
  </div>
  <div class="col-12">
    <label for="inputAddress2" class="form-label">Address 2</label>
    <input type="text" class="form-control" id="inputAddress2" placeholder="Apartment, studio, or floor">
  </div>
  <div class="col-md-6">
    <label for="inputCity" class="form-label">City</label>
    <input type="text" class="form-control" id="inputCity">
  </div>
  <div class="col-md-4">
    <label for="inputState" class="form-label">State</label>
    <select id="inputState" class="form-select">
      <option selected>Choose...</option>
      <option>...</option>
    </select>
  </div>
  <div class="col-md-2">
    <label for="inputZip" class="form-label">Zip</label>
    <input type="text" class="form-control" id="inputZip">
  </div>
  <div class="col-12">
    <div class="form-check">
      <input class="form-check-input" type="checkbox" id="gridCheck">
      <label class="form-check-label" for="gridCheck">
        Check me out
      </label>
    </div>
  </div>
  <div class="col-12">
    <button type="submit" class="btn btn-primary">Sign in</button>
  </div>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogg</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
  <%= render partial: "shared/navbar"%>
  <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div class=".container">
  <div class=".mx-auto">
  <a class="btn btn-outline-light" href="#"  role="button" aria-disabled="true">-------------------------------------------------------------</a>
  <a class="btn btn-primary" href="/sign_up" role="button">Sign Up</a>
  <a class="btn btn-outline-success" href="/sign_in" role="button">Sign_in</a>
  <a class="btn btn-outline-info" href="/jobs" role="button">Discover Jobs</a>
<hr>
  <%= render partial: "shared/jobs"%>
  </div>
</div>

app/views/password/edit.html.erb
<h1>Edit Password</h1>
<%= form_with model: Current.user, url: edit_password_path do |form| %>
<% if form.object.errors.any? %>
<div class:"alert alert-danger">
<% form.object.errors.full_messages.each do |message| %>
<div><%= message %> </div>
<% end %>
</div>
<% end %>

  <div class="mb-3">
<%= form.label :Password %>
<%= form.password_field :password, class: "form-control", placeholder: "**********" %>
  </div>
    <div class="mb-3">
<%= form.label :Password_Confirmation %>
<%= form.password_field :password_confirmation, class: "form-control", placeholder: "**********" %>
  </div>
  <%= form.submit "Update Password", class:"btn btn-primary" %>
<% end %>

app/views/password/edit_reset.html.erb
<h1>Reset Your Password</h1>
<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |form| %>
<% if form.object.errors.any? %>
<div class:"alert alert-danger">
<% form.object.errors.full_messages.each do |message| %>
<div><%= message %> </div>
<% end %>
</div>
<% end %>
      <div class="mb-3">
      <%= form.label :Password %>
      <%= form.password_field :password, class: "form-control", placeholder: "**********" %>
        </div>
          <div class="mb-3">
      <%= form.label :Password_Confirmation %>
      <%= form.password_field :Password_Confirmation, class: "form-control", placeholder: "**********" %>
        </div>
 <div class="mb-3">
  <%= form.submit "Reset Password", class:"btn btn-primary" %>
<% end %>

app/views/password/new_reset.html.erb
<h1> Forget Your Password?</h1>
<%= form_with url: password_reset_path do |form| %>
 <div class="mb-3">
<%= form.label :Email %>
<%= form.text_field :email, class: "form-control", placeholder: "ashqur@google.com" %>
  </div>
  <%= form.submit "Reset", class:"btn btn-primary" %>
<% end %>

app/views/session/new.html.erb
<%= form_with model:@user, url: sign_in_path do |form| %>
  <div class="mb-3">
<%= form.label :Email %>
<%= form.text_field :email, class: "form-control", placeholder: "ashqur@zen.com" %>
  </div>
  <div class="mb-3">
<%= form.label :Password %>
<%= form.password_field :password, class: "form-control", placeholder: "**********" %>
<%= link_to "Forget Your Password? ", password_reset_path %>
  </div>
  <%= form.submit "Log in", class:"btn btn-primary" %>
<% end %>

app/views/shared/_card.html.erb
<div class="card">
  <div class="card-header">
    Quote
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <p>A well-known quote, contained in a blockquote element.</p>
      <footer class="blockquote-footer">Someone famous in <cite title="Source Title">Source Title</cite></footer>
    </blockquote>
  </div>
</div>

app/views/shared/_flash.html.erb
<div class="alert alert-info mt-4" role="alert">
<%=
flash.now[:notice]
%>
</div>

app/views/shared/_jobs.html.erb
<br>
<div class=".container-fluid">
<% @job.each do |s| %>
    <%= form_with model:@job, url:  jobs_Applied_jobs_path do |form| %>
    <div class="alert alert-success" role="alert" >
  <h4 class="alert-heading"><%= s.title %></h4>
  <hr>
  <p style="margin-left:auto; margin-right:auto; width:60%; height: 200px; overflow-y: scroll;"> <%= s.description %> </p>
  <hr>
  <p class="mb-2"><%= s.created_at %> </p><%= form.submit "Apply", class:"btn btn-primary" %>
</div>
<% end %>
<% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
   <a class="navbar-brand" href="#"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-app-indicator" viewBox="0 0 16 16">
  <path d="M5.5 2A3.5 3.5 0 0 0 2 5.5v5A3.5 3.5 0 0 0 5.5 14h5a3.5 3.5 0 0 0 3.5-3.5V8a.5.5 0 0 1 1 0v2.5a4.5 4.5 0 0 1-4.5 4.5h-5A4.5 4.5 0 0 1 1 10.5v-5A4.5 4.5 0 0 1 5.5 1H8a.5.5 0 0 1 0 1H5.5z"/>
  <path d="M16 3a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
</svg> </a>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
        <%
        
=begin%>
 way to make links in consisistency 
 insted of  "<a class="nav-link" href="/about">About Us</a>"
<%
=end%>

        <%= link_to "About", about_path, class:"nav-link"  %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Menu
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="/jobs/Applied_jobs">Applied Jobs</a></li>
            <li><a class="dropdown-item" href="/jobs">All </a></li>
            <% if Current.user %>
            <li><hr class="dropdown-divider "></li>
            <% if Current.user.recruiter %>
            <li><a class="dropdown-item" href="/jobs/recruiter_applications">Applications </a></li> 
            <%end%>
            <li ><%= link_to "Logout", logout_path, method: :delete, class:"dropdown-item dropdown-menu-dark" %></li>
            <% end %>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-warning" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>